### PR TITLE
[13.0][MIG] l10n_ee_accounting & l10n_ee_reporting

### PR DESCRIPTION
**Pull request by alexey-pelykh**
Waiting for #4

### CODE REVIEW

**Comment by alexey-pelykh** [comment]
@sbidoul seems there's an issue with CI here

**Comment by sbidoul** [comment]
For 13.0 and up, please do `pipx run copier update` and answer GitHub to the CI question. I'm not trying to understand Travis issue anymore.

For older branche down to 10, `pipx run copier copy git+https://github.com/oca/oca-addons-repo/template .` - I'll communicate on this topic soon-ish.

**Comment by alexey-pelykh** [comment]
```
(env) root@90af17a3f982:/OCA/l10n-estonia# pipx run copier update
Cannot update because cannot obtain old template references from `.copier-answers.yml`.
```
@sbidoul sorry, any ideas?

**Comment by sbidoul** [comment]
Ah, right, it seems the 13.0 branch of this repo was not initialized with the template. So you need to initialize it with 

`pipx run copier copy git+https://github.com/oca/oca-addons-repo/template .`

**Pull request merged**
